# Generated by Django 4.2.2 on 2023-06-10 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='pictures',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tags',
        ),
    ]
