# Generated by Django 4.2.2 on 2023-06-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_project_total_target_donations'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pictures',
            field=models.ManyToManyField(blank=True, related_name='project_pictures', to='project.projectpicture'),
        ),
    ]
