# Generated by Django 4.2.2 on 2023-06-10 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_project_pictures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='pictures',
        ),
    ]
