# Generated by Django 4.2.2 on 2023-06-11 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_project_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='donation',
            field=models.IntegerField(default=0),
        ),
    ]
