# Generated by Django 4.2.2 on 2023-06-11 11:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_myuser_profile_picture'),
        ('project', '0008_projectreport_commentreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='averageRate',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ProjectRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.comments')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.myuser')),
            ],
        ),
    ]
