# Generated by Django 4.2.2 on 2023-06-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_project_averagerate_projectrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_selected_by_admin',
            field=models.BooleanField(default=0),
        ),
    ]
