# Generated by Django 4.2.2 on 2023-06-13 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_project_is_selected_by_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrate',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
    ]
