# Generated by Django 4.2.2 on 2023-06-10 12:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('mobile_phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^01[0-2,5]{1}[0-9]{8}$')])),
                ('profile_picture', models.ImageField(upload_to='profile_pictures')),
                ('is_active', models.BooleanField(default=True)),
                ('is_verifications', models.BooleanField(default=False)),
                ('is_authenticated', models.BooleanField(null=True)),
                ('auth_provider', models.CharField(default='email', max_length=255)),
                ('country', models.CharField(blank=True, max_length=30, null=True)),
                ('Birth_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
